[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =

    ignore:Inheritance class HomeAssistantApplication from web.Application is discouraged:DeprecationWarning
    ignore:coroutine 'WashDataManager\._async_perform_combined_matching' was never awaited:RuntimeWarning

