name: Bug Report
description: Create a report to help us improve HA WashData
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: "When I engage the flux capacitor, the washing machine assumes it's a coffee maker..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Integration Version
      description: What version of HA WashData are you running?
      placeholder: "v0.3.1"
    validations:
      required: true
  
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant Core are you running?
      placeholder: "2024.12.0"
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: debug_log
    attributes:
      label: Debug LOG
      description: |
        Please enable debug logging for `custom_components.ha_washdata` and `custom_components.ha_washdata.profile_store`.
        
        To enable via YAML:
        ```yaml
        logger:
          default: info
          logs:
            custom_components.ha_washdata: debug
        ```
      render: shell
